config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'setting/top'
  get 'setting/help'
  get 'setting/about'
  get 'setting/sort'

  get 'dig/task' => "tasks#dig"
  devise_for :users
  resources :tasks
  get "home/top" => "home#top"
  get "/"=>"home#top"

  devise_scope :user do
       get '/users/sign_out' => 'devise/sessions#destroy'
     end
   authenticated :users do
        root :to => "tasks#index"
    end

    unauthenticated :users do
        root :to => "home#top"
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    tasks_path
  end

  def after_sign_out_path_for(resource)
     home_top_path
  end

  
	
	protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
def top
   @task = Task.new
end

def about
	@task = Task.new
end

def help
	@task = Task.new
end

def sort
	@task = Task.new
end

def destroy
end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
# 認証済みであることを確認
before_action :authenticate_user!

def index
  @tasks = current_user.tasks.order("target_at DESC")
  @task = Task.new

  @taskParam = target_task params[:id]
end

def show
  @task = target_task params[:id]
end

def new
  @task = Task.new
end

def create
  @task = current_user.tasks.new task_params
  @task.save!
  redirect_to tasks_path
end

def edit
  @task = target_task params[:id]
end

def dig

end

def update
  @task = target_task params[:id]
  @task.update(task_params)
  redirect_to @task
end

def destroy
  @task = target_task params[:id]
  @task.destroy
  redirect_to tasks_url
end


private
def target_task task_id
  current_user.tasks.where(id: task_id).take
end

def task_params
  params.require(:task).permit(:title, :description, :target_at)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/top.html.erb
	<div class="backg_top">
	<div class="first">
<%= image_tag("icon.png" ,:class =>"main_icon")%>
<p>>Todo Capsule.</p>
 	</div>

 	<div class="buttons">

	<%= link_to 'Log In.',new_user_session_path , :class => "button_login" %>
    <%= link_to 'Sign Up.', new_user_registration_path, :class => "button_new" %> 	
 	</div>
 </div>




	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>ToDoCapsule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="theme-color" content="#df7401">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="<%=image_path("icon3.png")%>" />
</head>

  <body>
     <!-- <% if user_signed_in? %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
      <% if user_signed_in? %>
      username : <%= current_user.username %>さん
      <% end %>
      <% if user_signed_in? %>
      <%= link_to "たすくかんり","/tasks" %>
      <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->   
    <%= yield %>
    <script>
    $(function(){
  $('a').click(function(){
    location.href = $(this).attr('href');
    return false;
  });
  $('.input').on('touchstart',function(){
    console.log("a");
    $(".header-form-container").slideDown();
    $(".input").slideUp(700);
    $(".icon_slide").fadeIn();
    $(".bury_box").fadeIn(1000);
    $(".capsule").fadeOut(500);
    $(".icon_delate").slideUp();
    $(".message_del").slideUp(600);
    $(".message_del_but").slideUp(600);
    $(".deltab").fadeOut(600);
  }).css('cursor','pointer');



  $('.icon_delate').on('touchstart',function(){
    $(".message_del").slideDown(600);
    $(".message_del_but").slideDown(600);
    $(".deltab").fadeIn(600);
  }).css('cursor','pointer');



  $('.slidein').on('touchstart',function(){
    $(".header-form-container").slideUp(600);
    $(".input").slideDown();
    $(".icon_slide").fadeOut(500);
    $(".bury_box").fadeOut(500);
  }).css('cursor','pointer');


$('.icon_fade').on('touchstart',function(){
    $(".capsule").fadeOut(500);
    $(".icon_delate").slideUp();
    $(".message_del").slideUp(600);
    $(".message_del_but").slideUp(600);
    $(".deltab").fadeOut(600);
  }).css('cursor','pointer');



  $('.bury').on('touchstart',function(){
    $(".bury_box").fadeTo(300,0.1);
    $(".header-form-container").slideUp(1000);
    $(".input").slideDown();
    $(".icon_slide").fadeOut(500);
  }).css('cursor','pointer');


  var match = location.search.match(/id=(.*?)(&|$)/);
  console.log(match);

  if(match) {
      id = decodeURIComponent(match[1]);
      $(".capsule").fadeIn(500);
      $(".icon_delate").slideDown();
      $(".message_del").slideUp(600);
      $(".message_del_but").slideUp(600);
      $(".deltab").fadeOut(600);
  }

  $('.icon_fade').on('touchstart',function(){
    $(".capsule").fadeOut(500);
    $(".icon_delate").slideUp();
    $(".message_del").slideUp(600);
    $(".message_del_but").slideUp(600);
    $(".deltab").fadeOut(600);
  }).css('cursor','pointer');



  $('.but_bury').on('touchstart',function(){
    $(".bury_box").fadeTo(300,0.1);
    $(".header-form-container").slideUp(1000);
    $(".input").slideDown();
    $(".icon_slide").fadeOut(500);
    $(".capsule").fadeOut(500);
    $(".icon_delate").slideUp();
    $(".message_del").slideUp(600);
    $(".message_del_but").slideUp(600);
    $(".deltab").fadeOut(600);
    $(".backblack").fadeIn();
    $(".past_box").fadeIn(1500);
  }).css('cursor','pointer');


  $('.rec_but').on('touchstart',function(){
    $(".past_box").fadeOut(600);
    $(".backblack").fadeOut(1000);
  }).css('cursor','pointer');
})
</script>






  </body>
</html>

app/views/setting/about.html.erb
<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>

    </div>

    

  </header>


	<div class="set">

	<p class="set_title"> <span class="initial">> A</span>bout.</p>
	<p class="set_box">このアプリケーションは卓展2018において制作されたものです。</p>
	<p class="set_box_low">Created by Shakurri.</p>

	</div>
	      <%= image_tag("icon.png" ,:class => "backg_icon")%>



	
	<footer>
	      <%=link_to image_tag("back.png" ,:class => "icon_back"),setting_top_path%>
	</footer>

app/views/setting/help.html.erb
<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>

    </div>

    

  </header>


	<div class="set">

	<p class="set_title"> <span class="initial">> H</span>elp.</p>
	<p class="set_box">
		<span class="initial">> </span>このアプリの使い方<br><br>
		1.NewCapsuleで新規Capsuleを作成<br>
		　↓<br>
		2.内容・期日・伝言を入力<br>
		　↓<br>
		3.Buryで登録<br>
		　↓<br>
		4.期日になったらDigして伝言を受け取る
	</p>

	</div>
	      <%= image_tag("icon.png" ,:class => "backg_icon")%>



	
	<footer>
	      <%=link_to image_tag("back.png" ,:class => "icon_back"),setting_top_path%>
	</footer>

app/views/setting/sort.html.erb
<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>

    </div>

    

  </header>


	<div class="set">

	<p class="set_title"> <span class="initial">> S</span>ort.</p>
	<p class="set_box">
		<span class="initial">> </span>
    作成順
	</p>
  <p class="set_box">
    <span class="initial">> </span>
    期日順
  </p>
  <p class="set_box">
    <span class="initial">> </span>
    タイトル順
  </p>

	</div>
	      <%= image_tag("icon" ,:class => "backg_icon")%>



	
	<footer>
	      <%=link_to image_tag("back.png" ,:class => "icon_back"),setting_top_path%>
	</footer>

app/views/setting/top.html.erb
<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>

    </div>

    

  </header>


	<div class="set">

	<p class="set_title"><span class="initial">> S</span>etting.</p>


  <!--<%= link_to setting_sort_path do%>
	<p class="set_box"><span class="initial">> </span>Sort.</p>
  <%end%>-->
	<%= link_to setting_help_path do%>
	<p class="set_box"><span class="initial">> </span>Help.</p>
	<%end%>
	<%= link_to setting_about_path do%>
	<p class="set_box"><span class="initial">> </span>About.</p>
	<%end%>
	<%= link_to destroy_user_session_path, method: :delete do%>
	<p class="set_box"><span class="initial">> </span>Log Out.</p>
	<%end%>

	</div>
	      <%= image_tag("icon.png" ,:class => "backg_icon")%>



	
	<footer>
	      <%=link_to image_tag("back.png" ,:class => "icon_back"),tasks_path%>
	</footer>


app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>
<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, size: 50 %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/tasks/index.html.erb
<!-- <table>
  <tr>
    <th>Id</th><th>Title</th><th>Description</th><th></th><th></th><th></th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.id %></td>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task_path(task) %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
  </tr>
  <% end %>
</table> -->
<!-- 
<p>Find me in app/vlink_toiews/tasks/index.html.erb</p> -->
<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>
  </div>


  <table class="deltab">
    <td>
  <span class="message_del">
    Do you really want to delete?
  </span>
  </td>

  <td>
  <% if @taskParam %>
  <%= button_to task_path(@taskParam), method: :delete do%>
  <span class="message_del_but">
    Delete
  </span>
  <% end %>
  <% end %>
  </td>
  </table>


    

  </header>

  <div class="capsule">
    <% if @taskParam %>
    <p class="content">内容：<span class="content_m"><%= @taskParam.title %></span></p>
    <%= image_tag("slideup.png" ,:class => "icon_fade")%>
    <span class="limit">期日：
      <span class="month_m">
      <% if @taskParam.target_at %>
      <%= @taskParam.target_at.month %>
        <% end %>
      </span>月<span class="day_m">
        <% if @taskParam.target_at %>
      <%= @taskParam.target_at.day %>
      <% end %>
    </span>日</span>
    <span class="count">あと<span class="count_m">
    <% if @taskParam.target_at %>
      <% @taskParam.target_at.to_date %>
      <% @goal = @taskParam.target_at.to_date - Date.today %>
      <%if @goal.to_i > 0 %>
        <%= @goal.to_i %>
        <% else %>
        0
        <%end%>
    <% end %>
  </span>日</span>
    <p class="but_bury">Dig.</p>
    <% end %>
  </div>

<div class="backblack">
</div>


  <%if @taskParam%>
  <div class="past_box">

    <div class="relative">
      <%= image_tag("past_message.png" ,:class => "past_message")%>
      <%= image_tag("past.png" ,:class => "past_hum")%>
      <p class="you">
        <span class="month_m">
      <% if @taskParam.created_at %>
      <%= @taskParam.created_at.month %>
        <% end %>
      </span>月
      <span class="day_m">
        <% if @taskParam.created_at %>
      <%= @taskParam.created_at.day %>
      <% end %>
    </span>日の<br>
      あなたからのお言葉
    </p>


    <% if @taskParam %>
    <%= button_to task_path(@taskParam), method: :delete do%>
    <span class="rec_but">Receive.</span>
    <% end %>
    <% end %>



    <p class="time_message">
      <% if @taskParam.description %>
      <%= @taskParam.description %>
      <% end %>
    </p>

    </div>

  </div>
  <% end %>

  <div>
  <div class="main">
    <% @tasks.each do |task| %>
      <div>
        <%= link_to(tasks_path(id: task.id)) do %>
        <% if task.title %>
          <% task_box = task.title.split(//) %>
          <span class=title1><%= task_box[0] %></span>
          <span class=title2><%= task_box[1] %></span>
        <% end %>
        <% if task.target_at %>
          <span class=month><%= task.target_at.month %></span>
          <span class=day><%= task.target_at.day %></span>
        <% end %>
        <% if task.target_at %>
        <% task.target_at.to_date %>
        <% count = task.target_at.to_date - Date.today %>
          <% if count.to_i > 0 %>
            <%= image_tag("wrap.png" ,:class => "wrap")%>
          <% end %>
          <% end %>

        <% end %>
      </div>
    <% end %>
  </div>


  
  <footer>
  <%= image_tag("back.png" ,:class => "icon_back")%>
  <%= image_tag("delate.png",:class => "icon_delate")%>

  <%= link_to image_tag("more.png" ,:class => "icon_more"),setting_top_path%>

  </footer>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>
<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, size: 50 %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p>

app/views/tasks/show.html.erb
<!-- <h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>
<table>
  <tr>
    <th>Title</th>
    <td><%= @task.title %></td></tr>
  <tr>
    <th>Description</th>
    <td><%= @task.description %></td>
  </tr>
  <tr>
    <th>User.Email</th>
    <td><%= @task.user.email %></td>
  </tr>
</table>
<p><%= link_to '一覧に戻る', tasks_url %></p> -->

<header>
    <div class="input">
    <p>> New Capsule.</p>
    </div>

    <div class="header-form-container">
    <%= form_for(@task) do |f| %>
    <table class="form_box">
    <div>
      <tr>
      <td class="labels"><%= f.label :title, "内容:" %></td>
      <td><%= f.text_field :title, :class=>"field" %></td>
      <td class="slidein"><%= image_tag("slideup.png" ,:class => "icon_slide")%></td>
    </tr>
    </div>

    <tr>
    <div>
      <td class="labels"><%= f.label :taeget_at, "期日:" %></td>
      <td class="select"><%= f.date_select :target_at %></td>
    </div>
    </tr>



    <tr>
    <div>
      <td class="labels"><%= f.label :description, "伝言:" %></td>
      <td><%= f.text_area :description , :class=>"area"%></td>
    </div>
    <div>
      <td class="bury_box"><%= f.submit 'Bury.', :class=>"bury" %></td>
    </div>
    </tr>

    </div>
    <% end %>
  </table>

    </div>

    

  </header>


  <div class="capsule">
    <p class="content">内容：<span class="content_m">卓の課題</span></p>
    <span class="limit">期日：<span class="month_m">7</span>月<span class="day_m">30</span>日</span>
    <span class="count">あと<span class="count_m">5</span>日</span>
    <p class="but_bury">Digする!</p>




  </div>

  <div>
  <div class="main">
    
      <% @tasks.each do |task| %>
        <div>
          <% if task.title %>
            <% task_box = task.title.split(//) %>
            <span class=title1><%= task_box[0] %></span>
            <span class=title2><%= task_box[1] %></span>
          <% end %>
          <% if task.target_at %>
            <span class=month><%= task.target_at.month %></span>
            <span class=day><%= task.target_at.day %></span>
          <% end %>
          <%= image_tag("wrap.png" ,:class => "wrap")%>
        </div>
      <% end %>
        

    <div>
      <span class=month>7</span>
      <span class=day>30</span>
      <span class=title1>卓</span>
      <%= image_tag("wrap.png" ,:class => "wrap")%>
    </div>
  </div>


  
  <footer>
  <%= image_tag("back.png" ,:class => "icon_back")%>
  <%= image_tag("delate.png",:class => "icon_delate")%>

  <%= link_to image_tag("more.png" ,:class => "icon_more"),setting_top_path%>

  </footer>